import type { Fmp, TimelineEntry } from '@/types'

export const MOCK_FMPS: Fmp[] = [
  {
    id: 'mock-1',
    name: 'BlackRock Asia Pacific',
    relationship_manager: 'James Chen',
    market: 'Hong Kong',
    stage: 'Signed',
    sub_status: 'Complete',
    next_step: 'Schedule Q2 strategy review call with Sarah Kim to discuss fund registration timeline',
    next_contact_date: '2026-03-18',
    fmp_contact_name: 'Sarah Kim',
    fmp_contact_email: 'sarah.kim@blackrock.com',
    fmp_contact_role: 'Managing Director, Distribution',
    retainer_amount: 75000,
    fund_registration_fee: 15000,
    contract_status: 'Signed',
    contract_start_date: '2026-01-15',
    date_added: '2025-11-01',
    created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 'mock-2',
    name: 'Nomura Asset Management',
    relationship_manager: 'Yuki Tanaka',
    market: 'Japan',
    stage: 'Negotiation',
    sub_status: 'In Process',
    next_step: 'Send updated fund prospectus and await compliance sign-off',
    next_contact_date: '2026-03-10',
    fmp_contact_name: 'Hiroshi Nakamura',
    fmp_contact_email: 'h.nakamura@nomura.com',
    fmp_contact_role: 'Head of Alternative Investments',
    retainer_amount: 60000,
    fund_registration_fee: 12000,
    contract_status: 'Signed',
    contract_start_date: '2026-02-01',
    date_added: '2025-10-15',
    created_at: '2025-10-15T00:00:00Z',
  },
  {
    id: 'mock-3',
    name: 'Mirae Asset Global',
    relationship_manager: 'James Chen',
    market: 'Korea',
    stage: 'Prospect',
    sub_status: 'In Process',
    next_step: 'Initial introductory meeting — present Greenstone fund strategy and APAC track record',
    next_contact_date: '2026-03-25',
    fmp_contact_name: 'Ji-Young Park',
    fmp_contact_email: 'jy.park@miraeasset.com',
    fmp_contact_role: 'Senior Portfolio Manager',
    retainer_amount: null,
    fund_registration_fee: null,
    contract_status: 'Not Started',
    contract_start_date: null,
    date_added: '2026-01-10',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'mock-4',
    name: 'GIC Private Limited',
    relationship_manager: 'Rachel Lim',
    market: 'Singapore',
    stage: 'Signed',
    sub_status: 'Complete',
    next_step: 'Coordinate capital call schedule with operations team',
    next_contact_date: '2026-04-05',
    fmp_contact_name: 'Michael Tan',
    fmp_contact_email: 'm.tan@gic.com.sg',
    fmp_contact_role: 'Director, Private Equity',
    retainer_amount: 90000,
    fund_registration_fee: 20000,
    contract_status: 'Signed',
    contract_start_date: '2025-12-01',
    date_added: '2025-09-01',
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: 'mock-5',
    name: 'Cathay Life Insurance',
    relationship_manager: 'David Wu',
    market: 'Taiwan',
    stage: 'Issue Contract',
    sub_status: 'In Process',
    next_step: 'Follow up on regulatory approval for cross-border investment — target FSC clearance by end of Q1',
    next_contact_date: '2026-03-07',
    fmp_contact_name: 'Kevin Lin',
    fmp_contact_email: 'kevin.lin@cathaylife.com.tw',
    fmp_contact_role: 'VP, Investment Management',
    retainer_amount: 55000,
    fund_registration_fee: 10000,
    contract_status: 'Under Negotiation',
    contract_start_date: null,
    date_added: '2025-12-01',
    created_at: '2025-12-01T00:00:00Z',
  },
  {
    id: 'mock-6',
    name: 'Samsung Asset Management',
    relationship_manager: 'Yuki Tanaka',
    market: 'Korea',
    stage: 'First Call',
    sub_status: 'Complete',
    next_step: 'Send fund overview deck and schedule second call',
    next_contact_date: '2026-04-15',
    fmp_contact_name: null,
    fmp_contact_email: null,
    fmp_contact_role: null,
    retainer_amount: null,
    fund_registration_fee: null,
    contract_status: 'Not Started',
    contract_start_date: null,
    date_added: '2026-02-01',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'mock-7',
    name: 'Nikko Asset Management',
    relationship_manager: 'Yuki Tanaka',
    market: 'Japan',
    stage: 'Second Call',
    sub_status: 'In Process',
    next_step: 'Deliver updated deck incorporating new ESG reporting framework',
    next_contact_date: '2026-03-20',
    fmp_contact_name: 'Akiko Yamamoto',
    fmp_contact_email: 'a.yamamoto@nikkoam.com',
    fmp_contact_role: 'Executive Director',
    retainer_amount: 48000,
    fund_registration_fee: 8000,
    contract_status: 'Under Negotiation',
    contract_start_date: null,
    date_added: '2026-01-20',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'mock-8',
    name: 'Temasek Holdings',
    relationship_manager: 'Rachel Lim',
    market: 'Singapore',
    stage: 'Negotiation',
    sub_status: 'In Process',
    next_step: 'Finalize side-letter terms with legal team',
    next_contact_date: '2026-03-14',
    fmp_contact_name: 'Wei Ling Ho',
    fmp_contact_email: 'wl.ho@temasek.com.sg',
    fmp_contact_role: 'Managing Director',
    retainer_amount: 120000,
    fund_registration_fee: 25000,
    contract_status: 'Signed',
    contract_start_date: '2026-01-01',
    date_added: '2025-08-15',
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: 'mock-9',
    name: 'HSBC Global AM Hong Kong',
    relationship_manager: 'James Chen',
    market: 'Hong Kong',
    stage: 'Rejected',
    sub_status: 'Complete',
    next_step: 'Re-engage after Q2 — check if new fund mandate aligns',
    next_contact_date: null,
    fmp_contact_name: 'Charlotte Wong',
    fmp_contact_email: 'c.wong@hsbcglobalasset.com',
    fmp_contact_role: 'Director, Product',
    retainer_amount: null,
    fund_registration_fee: null,
    contract_status: 'Not Started',
    contract_start_date: null,
    date_added: '2025-07-01',
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'mock-10',
    name: 'Fubon Life Insurance',
    relationship_manager: 'David Wu',
    market: 'Taiwan',
    stage: 'First Call',
    sub_status: 'In Process',
    next_step: 'Submit fund information request to investment committee',
    next_contact_date: '2026-04-20',
    fmp_contact_name: 'Alan Chen',
    fmp_contact_email: 'alan.chen@fubon.com',
    fmp_contact_role: 'CIO',
    retainer_amount: null,
    fund_registration_fee: null,
    contract_status: 'Not Started',
    contract_start_date: null,
    date_added: '2026-02-15',
    created_at: '2026-02-15T00:00:00Z',
  },
]

export const MOCK_TIMELINE: Record<string, TimelineEntry[]> = {
  'mock-1': [
    {
      id: 't1-1',
      fmp_id: 'mock-1',
      date: '2026-03-10',
      summary: 'Quarterly review call with Sarah Kim. Discussed Q1 fund performance (+14.2% net), upcoming LP roadshow in May, and Hong Kong SFC registration status. Sarah confirmed internal approval committee meets March 28th. Strong momentum.',
      logged_by: 'James Chen',
      created_at: '2026-03-10T00:00:00Z',
    },
    {
      id: 't1-2',
      fmp_id: 'mock-1',
      date: '2026-02-14',
      summary: 'Sent updated fund prospectus and audited financials. Sarah confirmed receipt and has forwarded to compliance. Expected 3-week review window.',
      logged_by: 'James Chen',
      created_at: '2026-02-14T00:00:00Z',
    },
    {
      id: 't1-3',
      fmp_id: 'mock-1',
      date: '2026-01-22',
      summary: 'Contract signed. Kick-off call completed. Retainer payment confirmed for Feb 1st. Outlined Q1 registration milestones.',
      logged_by: 'James Chen',
      created_at: '2026-01-22T00:00:00Z',
    },
  ],
  'mock-4': [
    {
      id: 't4-1',
      fmp_id: 'mock-4',
      date: '2026-02-28',
      summary: 'Capital commitment confirmed at SGD 150M. Legal teams aligned on subscription docs. Michael flagged potential co-investment interest in Fund IV.',
      logged_by: 'Rachel Lim',
      created_at: '2026-02-28T00:00:00Z',
    },
  ],
  'mock-8': [
    {
      id: 't8-1',
      fmp_id: 'mock-8',
      date: '2026-03-05',
      summary: 'Side-letter negotiation call. Temasek requesting MFN clause and quarterly reporting package. Flagged to legal — response due March 12th.',
      logged_by: 'Rachel Lim',
      created_at: '2026-03-05T00:00:00Z',
    },
    {
      id: 't8-2',
      fmp_id: 'mock-8',
      date: '2026-01-18',
      summary: 'Introductory partner dinner at Marina Bay Sands. Wei Ling confirmed Temasek is actively expanding PE allocation by 8% in 2026. Very strong fit with our strategy.',
      logged_by: 'Rachel Lim',
      created_at: '2026-01-18T00:00:00Z',
    },
  ],
}
